ElearnApp/Areas/Admin/Controllers/CategoryController.cs
using ElearnApp.Data;
using ElearnApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ElearnApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Category> categories = await _context.Categories.ToListAsync();
            return View(categories);
        }

        public async Task<IActionResult> Detail(int id)
        {
            Category category = await _context.Categories.FirstOrDefaultAsync(m => m.Id == id);
            return View(category);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            bool exist = await _context.Categories.AnyAsync(m => m.Name.Trim() == category.Name.Trim());

            if (exist)
            {
                ModelState.AddModelError("Name", "Category already exist");
                return View();
            }

            await _context.Categories.AddAsync(new Category { Name = category.Name});


            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var exisProduct = await _context.Categories.FirstOrDefaultAsync(m => m.Id == id);
            _context.Categories.Remove(exisProduct);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

ElearnApp/Areas/Admin/Controllers/DashboardController.cs
using ElearnApp.Data;
using ElearnApp.Migrations;
using ElearnApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ElearnApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        private readonly AppDbContext _context;

        public DashboardController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int id)
        {
            Category category = await _context.Categories.FirstOrDefaultAsync(m=>m.Id == id);
            return View(category);
        }
    }
}

ElearnApp/Areas/Admin/Controllers/SliderController.cs
using ElearnApp.Data;
using ElearnApp.Models;
using ElearnApp.ViewModels.Admin.Slider;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;

namespace ElearnApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SliderController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Sliders.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null) return BadRequest();

            Slider slider = await _context.Sliders.FirstOrDefaultAsync(x => x.Id == id);

            if (slider == null) return NotFound();

            return View(slider);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Slider slider)
        {
            if(ModelState.IsValid)
            {
                return View();
            }
            
            string fileName = Guid.NewGuid().ToString() + "_" + slider.Photo.FileName;

            string path = Path.Combine(_env.WebRootPath,"assets/images",fileName);
            
            using(FileStream stream = new(path, FileMode.Create))
            {
                await slider.Photo.CopyToAsync(stream);
            }

            await _context.Sliders.AddAsync(new Slider { Title = slider.Title, Description = slider.Description, Image = fileName});
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var slider = await _context.Sliders.FindAsync(id);

            string existPath = Path.Combine(_env.WebRootPath, "assets/images", slider.Image);

            DeleteFile(existPath);

            _context.Sliders.Remove(slider);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
			if (id is null) return BadRequest();

			Slider slider = await _context.Sliders.FirstOrDefaultAsync(x => x.Id == id);

			if (slider == null) return NotFound();

            return View(new SliderEditVM { Image = slider.Image, Title = slider.Title, Description = slider.Description,Id = slider.Id});
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int? id, SliderEditVM request)
		{
			if (id is null) return BadRequest();

			Slider slider = await _context.Sliders.FirstOrDefaultAsync(x => x.Id == id);

			if (slider == null) return NotFound();

			if (request.Photo != null)
			{
				string existPath = Path.Combine(_env.WebRootPath, "assets/images", slider.Image);
				DeleteFile(existPath);

				string newFileName = Guid.NewGuid().ToString() + "_" + request.Photo.FileName;
				string newPath = Path.Combine(_env.WebRootPath, "assets/images", newFileName);

				using (FileStream stream = new(newPath, FileMode.Create))
				{
					await request.Photo.CopyToAsync(stream);
				}

				slider.Image = newFileName;
			}


			slider.Title = request.Title;
			slider.Description = request.Description;

			await _context.SaveChangesAsync();

			return RedirectToAction(nameof(Index));
		}


		private void DeleteFile(string path)
        {
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
        }
    }
}

ElearnApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Startmin - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/admin/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="~/admin/css/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="~/admin/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="~/admin/css/startmin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="~/admin/css/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="~/admin/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <a class="navbar-brand" href="">Startmin</a>
            </div>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <ul class="nav navbar-nav navbar-left navbar-top-links">
                <li><a asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home fa-fw"></i> Website</a></li>
            </ul>

            <!-- /.navbar-top-links -->
        </nav>

        <aside class="sidebar navbar-default" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a asp-controller="Dashboard" asp-action="Index" class="active"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a asp-controller="Category" asp-action="Index"><i class="fa fa-table fa-fw"></i> Category</a>
                    </li>
                    <li>
                        <a asp-controller="Slider" asp-action="Index"><i class="fa fa-table fa-fw"></i> Slider</a>
                    </li>
                    
                </ul>
            </div>
        </aside>
        <!-- /.sidebar -->
        @RenderBody()
        <!-- /.panel-body -->
        <div class="panel-footer">
            <div class="input-group">
                <span class="input-group-btn">
                        
                </span>
            </div>
        </div>
        <!-- /.panel-footer -->
    </div>
    <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/admin//js/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="~/admin//js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/admin//js/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="~/admin//js/raphael.min.js"></script>
    <script src="~/admin//js/morris.min.js"></script>
    <script src="~/admin//js/morris-data.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/admin//js/startmin.js"></script>

</body>

</html>